
name: Build

permissions:
  contents: read
  actions: read
  checks: write
  # Only allow writing checks, everything else is read-only

on:
  push:
    branches:
      - master
  pull_request:
    branches:
      - master

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Node.js
        uses: actions/setup-node@v3
        with:
          node-version: "20"
      
      - name: Install package dependencies
        run: npx pnpm i

      - name: Lint with ESLint
        run: npm run lint

      - name: Build
        run: npm run build
